import React, { useState, useEffect, useMemo } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { Sparkles, Zap, CheckCircle2, AlertCircle, Loader2, Send, Search, X } from 'lucide-react';
import { fetchMeta, createBrief, draftBriefAI } from '../api';
import { TOOL_CATEGORIES } from '../data/aiToolsData';

export function NewBriefPage() {
  const navigate = useNavigate();
  const [meta, setMeta] = useState(null);

  // AI Prompt State
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  const [aiMessage, setAiMessage] = useState(null);

  // Tool filtering in brief form
  const [toolSearch, setToolSearch] = useState('');
  const [toolCategory, setToolCategory] = useState('all');

  // Form State
  const [form, setForm] = useState({
    brand_id: 'br_01',
    title: '',
    campaign_goal: '',
    description: '',
    content_type_id: 1,
    style: '',
    aspect_ratio: '16:9',
    duration_sec: 30,
    deliverables_count: 1,
    budget_min_inr: 15000,
    budget_max_inr: 50000,
    deadline: '',
    commercial_use: 'full_buyout',
    usage_region: 'Global',
    required_tool_ids: [],
    required_skill_ids: []
  });

  const [errors, setErrors] = useState({});
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState(null);

  useEffect(() => {
    fetchMeta()
      .then(data => {
        setMeta(data);
        if (data.content_types && data.content_types.length > 0) {
          setForm(prev => ({ ...prev, content_type_id: data.content_types[0].id }));
        }
      })
      .catch(err => console.error('Failed to fetch meta:', err));
  }, []);

  const filteredTools = useMemo(() => {
    const list = meta?.tools || [];
    return list.filter(t => {
      const matchCat = toolCategory === 'all' ||
        (t.category_name && t.category_name.toLowerCase().includes(toolCategory.toLowerCase())) ||
        (t.category && t.category.toLowerCase() === toolCategory.toLowerCase());
      const matchSearch = !toolSearch ||
        t.name.toLowerCase().includes(toolSearch.toLowerCase()) ||
        (t.category_name && t.category_name.toLowerCase().includes(toolSearch.toLowerCase()));
      return matchCat && matchSearch;
    });
  }, [meta?.tools, toolCategory, toolSearch]);

  // Handle AI Draft Request
  const handleGenerateAI = async () => {
    if (!aiPrompt.trim()) return;
    setAiLoading(true);
    setAiMessage(null);

    try {
      const draft = await draftBriefAI(aiPrompt);
      setForm(prev => ({
        ...prev,
        title: draft.title || prev.title,
        campaign_goal: draft.campaign_goal || prev.campaign_goal,
        description: draft.description || prev.description,
        content_type_id: draft.content_type_id || prev.content_type_id,
        style: draft.style || prev.style,
        aspect_ratio: draft.aspect_ratio || prev.aspect_ratio,
        duration_sec: draft.duration_sec || prev.duration_sec,
        deliverables_count: draft.deliverables_count || prev.deliverables_count,
        budget_min_inr: draft.budget_min_inr || prev.budget_min_inr,
        budget_max_inr: draft.budget_max_inr || prev.budget_max_inr,
        deadline: draft.deadline || prev.deadline,
        commercial_use: draft.commercial_use || prev.commercial_use,
        usage_region: draft.usage_region || prev.usage_region,
        required_tool_ids: draft.required_tool_ids || prev.required_tool_ids,
        required_skill_ids: draft.required_skill_ids || prev.required_skill_ids
      }));

      if (draft.ai_generated) {
        setAiMessage({ type: 'success', text: 'Brief draft generated by Gemini AI model!' });
      } else {
        setAiMessage({ type: 'info', text: 'Generated using rule-based keyword extractor fallback.' });
      }
    } catch (err) {
      setAiMessage({ type: 'error', text: err.message || 'Failed to draft brief with AI.' });
    } finally {
      setAiLoading(false);
    }
  };

  // Field updates
  const handleChange = (field, val) => {
    setForm(prev => ({ ...prev, [field]: val }));
    if (errors[field]) {
      setErrors(prev => ({ ...prev, [field]: null }));
    }
  };

  const toggleTool = (toolId) => {
    setForm(prev => {
      const exists = prev.required_tool_ids.includes(toolId);
      const updated = exists
        ? prev.required_tool_ids.filter(id => id !== toolId)
        : [...prev.required_tool_ids, toolId];
      return { ...prev, required_tool_ids: updated };
    });
  };

  const toggleSkill = (skillId) => {
    setForm(prev => {
      const exists = prev.required_skill_ids.includes(skillId);
      const updated = exists
        ? prev.required_skill_ids.filter(id => id !== skillId)
        : [...prev.required_skill_ids, skillId];
      return { ...prev, required_skill_ids: updated };
    });
  };

  // Inline Validation
  const validateForm = () => {
    const errs = {};
    if (!form.title || form.title.trim().length < 3) {
      errs.title = 'Title must be at least 3 characters long.';
    }
    if (form.budget_min_inr && form.budget_max_inr && parseInt(form.budget_min_inr) > parseInt(form.budget_max_inr)) {
      errs.budget = 'Minimum budget cannot exceed maximum budget.';
    }
    setErrors(errs);
    return Object.keys(errs).length === 0;
  };

  // Submit Brief
  const handleSubmit = async (e) => {
    e.preventDefault();
    setSubmitError(null);
    if (!validateForm()) return;

    setSubmitting(true);
    try {
      const payload = {
        ...form,
        content_type_id: parseInt(form.content_type_id),
        duration_sec: form.duration_sec ? parseInt(form.duration_sec) : 30,
        deliverables_count: form.deliverables_count ? parseInt(form.deliverables_count) : 1,
        budget_min_inr: form.budget_min_inr ? parseInt(form.budget_min_inr) : 10000,
        budget_max_inr: form.budget_max_inr ? parseInt(form.budget_max_inr) : 50000
      };
      const created = await createBrief(payload);
      navigate(`/briefs/${created.id}`);
    } catch (err) {
      setSubmitError(err.message || 'Failed to submit campaign brief.');
      setSubmitting(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-10">

      {/* Header */}
      <div>
        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight flex items-center gap-3">
          <Sparkles className="w-7 h-7 text-indigo-600" />
          Create AI Campaign Brief
        </h1>
        <p className="text-xs text-slate-500 mt-1">
          Post your generative AI video, animation, or visual requirements to receive creator match scores.
        </p>
      </div>

      {/* AI Assistant Section */}
      <div className="p-6 rounded-3xl border border-indigo-200 bg-gradient-to-r from-indigo-50 via-purple-50 to-white shadow-xs space-y-4">
        <div className="flex items-center gap-2 text-indigo-900 font-bold text-sm">
          <Zap className="w-5 h-5 text-indigo-600" />
          Bonus: AI-Assisted Brief Builder
        </div>

        <p className="text-xs text-slate-700 leading-relaxed">
          Describe your campaign idea in rough prose (e.g. "I need a 15-second vertical social reel for a sports shoe launch using Sora and Runway with 40k budget"):
        </p>

        <div className="flex flex-col sm:flex-row gap-3">
          <input
            type="text"
            value={aiPrompt}
            onChange={(e) => setAiPrompt(e.target.value)}
            placeholder="Describe your creative idea roughly..."
            className="flex-1 px-4 py-3 rounded-xl bg-white border border-slate-300 text-slate-900 placeholder-slate-400 text-sm focus:outline-none focus:border-indigo-600 shadow-xs"
          />
          <button
            type="button"
            onClick={handleGenerateAI}
            disabled={aiLoading || !aiPrompt.trim()}
            className="px-6 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 disabled:opacity-50 text-white font-bold text-xs flex items-center justify-center gap-2 transition-all shadow-md shadow-indigo-600/20 shrink-0"
          >
            {aiLoading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Generating...
              </>
            ) : (
              <>
                <Sparkles className="w-4 h-4" />
                Prefill Form with AI
              </>
            )}
          </button>
        </div>

        {aiMessage && (
          <div className={`p-3 rounded-xl text-xs font-medium flex items-center gap-2 ${aiMessage.type === 'success'
              ? 'bg-emerald-50 text-emerald-800 border border-emerald-200'
              : aiMessage.type === 'info'
                ? 'bg-indigo-50 text-indigo-800 border border-indigo-200'
                : 'bg-rose-50 text-rose-800 border border-rose-200'
            }`}>
            <CheckCircle2 className="w-4 h-4 shrink-0" />
            {aiMessage.text}
          </div>
        )}
      </div>

      {/* Main Brief Form */}
      <form onSubmit={handleSubmit} className="bg-white p-6 sm:p-8 rounded-3xl border border-slate-200 space-y-6 shadow-xs">

        {submitError && (
          <div className="p-4 rounded-2xl bg-rose-50 border border-rose-200 text-rose-700 text-xs flex items-center gap-2">
            <AlertCircle className="w-5 h-5 shrink-0" />
            {submitError}
          </div>
        )}

        {/* Campaign Title */}
        <div>
          <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
            Campaign Title *
          </label>
          <input
            type="text"
            value={form.title}
            onChange={(e) => handleChange('title', e.target.value)}
            placeholder="e.g. Neo-Cyberpunk Sneaker Launch Social Reel"
            className={`w-full px-4 py-2.5 rounded-xl bg-white border text-slate-900 text-sm focus:outline-none ${errors.title ? 'border-rose-500' : 'border-slate-300 focus:border-indigo-600'
              }`}
          />
          {errors.title && <p className="text-xs text-rose-600 mt-1">{errors.title}</p>}
        </div>

        {/* Campaign Goal */}
        <div>
          <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
            Campaign Goal
          </label>
          <input
            type="text"
            value={form.campaign_goal}
            onChange={(e) => handleChange('campaign_goal', e.target.value)}
            placeholder="e.g. Drive viral engagement on Instagram Reels and TikTok"
            className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
          />
        </div>

        {/* Full Creative Description */}
        <div>
          <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
            Detailed Description / Prompt Guidelines
          </label>
          <textarea
            rows="4"
            value={form.description}
            onChange={(e) => handleChange('description', e.target.value)}
            placeholder="Provide aesthetic details, camera motions, visual references..."
            className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
          />
        </div>

        {/* Content Format & Style */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          <div>
            <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
              Content Format *
            </label>
            <select
              value={form.content_type_id}
              onChange={(e) => handleChange('content_type_id', e.target.value)}
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
            >
              {meta?.content_types?.map(ct => (
                <option key={ct.id} value={ct.id}>{ct.name}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
              Visual Style
            </label>
            <input
              type="text"
              value={form.style}
              onChange={(e) => handleChange('style', e.target.value)}
              placeholder="e.g. Hyper-realistic 3D, Anime, Photoreal"
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
            />
          </div>
        </div>

        {/* Aspect Ratio, Duration, Deliverables */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
          <div>
            <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
              Aspect Ratio
            </label>
            <select
              value={form.aspect_ratio}
              onChange={(e) => handleChange('aspect_ratio', e.target.value)}
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
            >
              {meta?.aspect_ratios?.map(ar => (
                <option key={ar} value={ar}>{ar}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
              Duration (Seconds)
            </label>
            <input
              type="number"
              value={form.duration_sec}
              onChange={(e) => handleChange('duration_sec', e.target.value)}
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
            />
          </div>

          <div>
            <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
              Deliverables Count
            </label>
            <input
              type="number"
              min="1"
              value={form.deliverables_count}
              onChange={(e) => handleChange('deliverables_count', e.target.value)}
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
            />
          </div>
        </div>

        {/* Budget Range (INR) */}
        <div>
          <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
            Budget Range (INR)
          </label>
          <div className="grid grid-cols-2 gap-4">
            <input
              type="number"
              value={form.budget_min_inr}
              onChange={(e) => handleChange('budget_min_inr', e.target.value)}
              placeholder="Min Budget"
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
            />
            <input
              type="number"
              value={form.budget_max_inr}
              onChange={(e) => handleChange('budget_max_inr', e.target.value)}
              placeholder="Max Budget"
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
            />
          </div>
          {errors.budget && <p className="text-xs text-rose-600 mt-1">{errors.budget}</p>}
        </div>

        {/* Commercial Use & Region */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          <div>
            <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
              Commercial Use Requirement
            </label>
            <select
              value={form.commercial_use}
              onChange={(e) => handleChange('commercial_use', e.target.value)}
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
            >
              <option value="full_buyout">Full Buyout (All media & perpetuity)</option>
              <option value="social_only">Social Media Only</option>
              <option value="internal_only">Internal Use Only</option>
            </select>
          </div>

          <div>
            <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-1.5">
              Usage Region
            </label>
            <input
              type="text"
              value={form.usage_region}
              onChange={(e) => handleChange('usage_region', e.target.value)}
              placeholder="e.g. Global, India, APAC"
              className="w-full px-4 py-2.5 rounded-xl bg-white border border-slate-300 text-slate-900 text-sm focus:outline-none focus:border-indigo-600"
            />
          </div>
        </div>

        {/* Required Tools Checkboxes */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="text-xs font-bold text-slate-700 uppercase tracking-wider">
              Required AI Tools ({form.required_tool_ids.length} selected)
            </label>
            {form.required_tool_ids.length > 0 && (
              <button
                type="button"
                onClick={() => setForm(prev => ({ ...prev, required_tool_ids: [] }))}
                className="text-[11px] text-indigo-600 hover:underline font-semibold"
              >
                Clear Tools
              </button>
            )}
          </div>

          {/* Quick Search & Category Dropdown */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mb-2.5">
            <div className="relative">
              <Search className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                value={toolSearch}
                onChange={(e) => setToolSearch(e.target.value)}
                placeholder="Search tools (e.g. Runway, Midjourney, Kling)..."
                className="w-full pl-8 pr-6 py-1.5 text-xs bg-slate-50 border border-slate-200 rounded-lg focus:outline-none focus:border-indigo-500 text-slate-800"
              />
              {toolSearch && (
                <button
                  type="button"
                  onClick={() => setToolSearch('')}
                  className="absolute right-2 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600"
                >
                  <X className="w-3 h-3" />
                </button>
              )}
            </div>

            <select
              value={toolCategory}
              onChange={(e) => setToolCategory(e.target.value)}
              className="w-full bg-slate-50 border border-slate-200 rounded-lg text-xs text-slate-700 p-1.5 focus:outline-none focus:border-indigo-500"
            >
              <option value="all">All 18 Categories ({meta?.tools?.length || 250}+ tools)</option>
              {TOOL_CATEGORIES.map(c => (
                <option key={c.id} value={c.name}>
                  {c.emoji} {c.name}
                </option>
              ))}
            </select>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2.5 max-h-48 overflow-y-auto p-3 bg-slate-50 rounded-xl border border-slate-200 custom-scrollbar">
            {filteredTools.length === 0 ? (
              <p className="col-span-full text-xs text-slate-400 py-2 text-center">
                No tools match "{toolSearch}"
              </p>
            ) : (
              filteredTools.map(t => (
                <label key={t.id} className="flex items-center gap-2 text-xs text-slate-700 cursor-pointer hover:text-slate-900 group">
                  <input
                    type="checkbox"
                    checked={form.required_tool_ids.includes(t.id)}
                    onChange={() => toggleTool(t.id)}
                    className="rounded border-slate-300 bg-white text-indigo-600 focus:ring-indigo-500 shrink-0"
                  />
                  <span className="truncate">{t.name}</span>
                </label>
              ))
            )}
          </div>
          <div className="flex items-center justify-between text-[11px] text-slate-400 mt-1">
            <span>Showing {filteredTools.length} of {meta?.tools?.length || 0} tools</span>
            <Link to="/tools" target="_blank" className="text-indigo-600 hover:underline font-medium">
              View Tool Catalog ↗
            </Link>
          </div>
        </div>

        {/* Required Skills Checkboxes */}
        <div>
          <label className="text-xs font-bold text-slate-700 uppercase tracking-wider block mb-2">
            Required Skills
          </label>
          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2.5 max-h-48 overflow-y-auto p-3 bg-slate-50 rounded-xl border border-slate-200 custom-scrollbar">
            {meta?.skills?.map(s => (
              <label key={s.id} className="flex items-center gap-2 text-xs text-slate-700 cursor-pointer hover:text-slate-900">
                <input
                  type="checkbox"
                  checked={form.required_skill_ids.includes(s.id)}
                  onChange={() => toggleSkill(s.id)}
                  className="rounded border-slate-300 bg-white text-indigo-600 focus:ring-indigo-500"
                />
                <span>{s.name}</span>
              </label>
            ))}
          </div>
        </div>

        {/* Form Submit Row */}
        <div className="pt-6 border-t border-slate-200 flex items-center justify-end gap-4">
          <button
            type="button"
            onClick={() => navigate('/briefs')}
            className="px-5 py-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold transition-colors"
          >
            Cancel
          </button>

          <button
            type="submit"
            disabled={submitting}
            className="px-8 py-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-bold shadow-md shadow-indigo-600/20 flex items-center gap-2 transition-all hover:scale-105"
          >
            {submitting ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Publishing...
              </>
            ) : (
              <>
                <Send className="w-4 h-4" />
                Publish Brief & Calculate Creator Matches
              </>
            )}
          </button>
        </div>

      </form>
    </div>
  );
}
